import "./globals.css";
import { Poppins } from "next/font/google";
import ToasterProvider from "./Providers/ToasterProvider";

const poppins = Poppins({
  subsets: ["devanagari"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToasterProvider />
        <div>{children}</div>
      </body>
    </html>
  );
}
