import "./globals.css";
import { Nunito } from "next/font/google";
import ToasterProvider from "../Providers/ToasterProvider";
import Navbar from "../components/Navbar";

const poppins = Nunito({
  subsets: ["latin"],
  weight: "500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToasterProvider />
        <div className="flex flex-col h-screen w-screen">
          <Navbar />
          <div className="flex-1 w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
